### ISSUE TITLE
No longer working in VS Code 1.31

### ISSUE THREAD

**Issue by KamasamaK** [humy2833/FTP-Simple#177]
After upgrading VS Code to 1.31, this extension no longer works. I am not seeing any error being generated either.

**Comment by joakim-emagine** [comment]
Actually having the same issue, error in developer console:

```
dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/joakimgeorge/.vscode/extensions/humy2833.ftp-simple-0.6.8/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/joakimgeorge/.vscode/extensions/humy2833.ftp-simple-0.6.8/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace
```

MAC OSX 10.14.2
VSCode Version 1.31.0 (1.31.0)

**Comment by shayzun** [comment]
I am having the same issue too, but like KamasamaK I am not getting any error.

**Comment by oingdoing** [comment]
I am having the same issue too!

**Comment by BSwaND** [comment]
Me too...

**Comment by lgArlequin** [comment]
same here!

**Comment by AlejoGonzalezU** [comment]
I thought it was just me, looks like it doesn't work anymore since the last update...

**Comment by humy2833** [comment]
This error is fixed by updating to this plugin version 0.6.9.
If you continue to experience problems, it may be due to an error in the plug-in other than this plug-in.
Please disable each other plug-in.

**Comment by yachawm** [comment]
macOS 10.13.6
VSCode 1.31.0

I formatted my macbook pro, and install macOS and VSCode. but now ftp-simple doesn't work anymore.

can download directory and file list, but not contents. 

even though click any files, doesn't download contents.

need to fix problem.

thanks.

**Comment by aramdry** [comment]
win 10 64 bit
VSCode 1.31.0

don't work remote directory open to work function. 
can download directory and file list, but not contents.

even though click any files, doesn't download contents.

need to fix problem.

**Comment by KamasamaK** [comment]
0.6.9 has not fixed the issue. To be clear, I've found that upload does work, but download/diff does not.

**Comment by ornoth** [comment]
MacOS 10.13.6
VSC 1.31.0
ftp-simple 0.6.9

Same error verified happening using 0.6.9, no information in output or debug consoles.

**Comment by Matt-Thew** [comment]
same here after update mac OS 10.14.3
vs code 1.31.0 
ftp-simplet 0.6.9

don't work remote directory open to work function.
can download directory and file list, but not contents.

**Comment by Matt-Thew** [comment]
> same here after update mac OS 10.14.3
> vs code 1.31.0
> ftp-simplet 0.6.9
> 
> don't work remote directory open to work function.
> can download directory and file list, but not contents.

after downgrade to 1.30.0 it works totally fine.

**Comment by humy2833** [comment]
We apologize for any inconvenience.
There was a problem with the internal ftp module that was being used when VSCode version 1.31 was upgraded.
Please use VSCode downgrade (1.30) while correcting the problem.
(Try "type" with "ftp2" instead of "ftp".
"ftp2" will attempt to connect to another module internally. But it may not.)

**Comment by KamasamaK** [comment]
I've just tested with v0.7.0 and the issue seems to be resolved.

**Comment by ornoth** [comment]
Verified success w/v0.7.0
